name: Deploy doc

on:
  # Runs on pushes targeting the main branch (uncomment to next 3 lines to enable)
  #  push:
  #    branches:
  #      - main
  #      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: make install-poetry

      - name: Pypi authentication
        run: |
          poetry config repositories.owkin https://pypi.owkin.com/simple/
          poetry config http-basic.owkin "${{ secrets.PYPI_USERNAME }}" "${{ secrets.PYPI_PASSWORD }}"

          poetry config repositories.sowce https://github.com/owkin/sowce.git
          poetry config http-basic.sowce "${{ secrets.GIT_USERNAME }}" "${{ secrets.GIT_TOKEN }}"

      - name: Install dependencies
        run: poetry install --all-extras --with=docs

      - name: Build docs
        run: poetry run make docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
